// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gens

const TableNameArea = "area"

// Area 区域表
type Area struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;not null;comment:区域名称" json:"name"` // 区域名称
	Pid  int32  `gorm:"column:pid;not null;comment:城市id" json:"pid"`   // 城市id
}

// TableName Area's table name
func (*Area) TableName() string {
	return TableNameArea
}
