// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gens

import (
	"time"
)

const TableNameAuUserAddress = "au_user_address"

// AuUserAddress 用户收货地址
type AuUserAddress struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;not null;comment:收件人" json:"name"`                        // 收件人
	Mobile     string    `gorm:"column:mobile;not null;comment:手机号" json:"mobile"`                    // 手机号
	ProvinceID int32     `gorm:"column:province_id;not null;comment:省份" json:"province_id"`           // 省份
	CityID     int32     `gorm:"column:city_id;not null;comment:城市" json:"city_id"`                   // 城市
	AreaID     int32     `gorm:"column:area_id;not null;comment:区域" json:"area_id"`                   // 区域
	Address    string    `gorm:"column:address;not null;comment:详细地址" json:"address"`                 // 详细地址
	UID        int32     `gorm:"column:uid;not null;comment:用户" json:"uid"`                           // 用户
	Status     int32     `gorm:"column:status;not null;default:2;comment:1->默认,2->非默认" json:"status"` // 1->默认,2->非默认
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName AuUserAddress's table name
func (*AuUserAddress) TableName() string {
	return TableNameAuUserAddress
}
