// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gens

const TableNameCity = "city"

// City 城市表
type City struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;not null;comment:城市名称" json:"name"` // 城市名称
	Pid  int32  `gorm:"column:pid;not null;comment:省份id" json:"pid"`   // 省份id
}

// TableName City's table name
func (*City) TableName() string {
	return TableNameCity
}
