// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gens

const TableNameProvince = "province"

// Province 省份表
type Province struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;not null;comment:省份名称" json:"name"` // 省份名称
}

// TableName Province's table name
func (*Province) TableName() string {
	return TableNameProvince
}
