// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gens

const TableNameStreet = "street"

// Street 街道表
type Street struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;not null;comment:街道名称" json:"name"` // 街道名称
	Pid  int32  `gorm:"column:pid;not null;comment:区域id" json:"pid"`   // 区域id
}

// TableName Street's table name
func (*Street) TableName() string {
	return TableNameStreet
}
