// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gens

import (
	"time"
)

const TableNameWaUser = "wa_users"

// WaUser 用户表
type WaUser struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`               // 主键
	Username  string    `gorm:"column:username;not null;comment:用户名" json:"username"`                       // 用户名
	Nickname  string    `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`                        // 昵称
	Password  string    `gorm:"column:password;not null;comment:密码" json:"password"`                        // 密码
	Sex       string    `gorm:"column:sex;not null;default:1;comment:性别" json:"sex"`                        // 性别
	Avatar    string    `gorm:"column:avatar;comment:头像" json:"avatar"`                                     // 头像
	Email     string    `gorm:"column:email;comment:邮箱" json:"email"`                                       // 邮箱
	Mobile    string    `gorm:"column:mobile;comment:手机" json:"mobile"`                                     // 手机
	Level     int32     `gorm:"column:level;not null;comment:等级" json:"level"`                              // 等级
	Birthday  time.Time `gorm:"column:birthday;comment:生日" json:"birthday"`                                 // 生日
	Money     float64   `gorm:"column:money;not null;default:0.00;comment:余额(元)" json:"money"`              // 余额(元)
	Score     int32     `gorm:"column:score;not null;comment:积分" json:"score"`                              // 积分
	LastTime  time.Time `gorm:"column:last_time;comment:登录时间" json:"last_time"`                             // 登录时间
	LastIP    string    `gorm:"column:last_ip;comment:登录ip" json:"last_ip"`                                 // 登录ip
	JoinTime  time.Time `gorm:"column:join_time;default:CURRENT_TIMESTAMP;comment:注册时间" json:"join_time"`   // 注册时间
	JoinIP    string    `gorm:"column:join_ip;comment:注册ip" json:"join_ip"`                                 // 注册ip
	Token     string    `gorm:"column:token;comment:token" json:"token"`                                    // token
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                           // 更新时间
	Role      int32     `gorm:"column:role;not null;default:1;comment:角色" json:"role"`                      // 角色
	Status    int32     `gorm:"column:status;not null;comment:禁用" json:"status"`                            // 禁用
	WxOpenID  string    `gorm:"column:wx_open_id;not null;comment:微信openid" json:"wx_open_id"`              // 微信openid
}

// TableName WaUser's table name
func (*WaUser) TableName() string {
	return TableNameWaUser
}
